version: '3'
services:
  pg_ppal:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_ppal
      POSTGRES_USER: postgres_ppal
      POSTGRES_PASSWORD: postgres_ppal
    ports:
      - "5432:5432"
    volumes:
      - pg_data_ppal:/var/lib/postgresql/data

  pg_slave1:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_slave1
      POSTGRES_USER: postgres_slave1
      POSTGRES_PASSWORD: postgres_slave1
    ports:
      - "5433:5432"
    volumes:
      - pg_data_slave1:/var/lib/postgresql/data

  cliente_ppal:
    build: ./cliente_ppal
    depends_on:
      - pg_ppal

  cliente_slave:
    build: ./cliente_slave
    depends_on:
      - pg_slave1

  oracle:  # Servicio de Oracle
    image: gvenzl/oracle-free:slim
    environment:
      - ORACLE_PASSWORD=oracle
    ports:
      - "1521:1521"

  etl:  # Nuevo servicio para el script ETL
    build: ./etl  # Ubicación del Dockerfile del ETL
    depends_on:
      - pg_ppal
      - pg_slave1
      - oracle
    links:
      - pg_ppal
      - pg_slave1
      - oracle
    environment:
      ORACLE_HOME: /opt/oracle  # Configuración de Oracle Instant Client
      LD_LIBRARY_PATH: /opt/oracle
    volumes:
      - /mnt/d/apps/instantclient-basic-linux.x64-23.6.0.24.10/instantclient_23_6:/opt/oracle  # Montar el código ETL en el contenedor

volumes:
  pg_data_ppal:
  pg_data_slave1:
