SELECT DR_NO, DATE_RPTD, AREA_NAME, CRM_CD_DESC, DATE_OCC, TIME_OCC, AREA, RPT_DIST_NO, "Part1-2", CRM_CD, MOCODES, VICT_AGE, VICT_SEX, VICT_DESCENT, PREMIS_CD
FROM ETL.TRANSFORMACION2;

SELECT count(*)
FROM ETL.TRANSFORMACION2;