version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - e11evenn  

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - e11evenn  

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /mnt/d/repos-sistemas-distribuidos/sistemas-distribuidos/docker-compose/E11EVENN:/docker-entrypoint-initdb.d
    networks:
      - e11evenn 

volumes:
  postgres_data:

networks:
  e11evenn:
    driver: bridge